### ISSUE TITLE
咨询一下作者关于代理设置

### ISSUE THREAD

**Issue by fanvinga** [icymind/VRouter#15]
目前情况是宿主机上有一个finalspeed客户端.连接了远程服务器的某个端口并映射为本地的630端口.mac分配到的ip地址为192.168.1.2或者192.168.1.3.请问如果要在vrouter中填写ssr服务器地址.应该填写127.0.0.1呢还是192.168.1.2

**Comment by fanvinga** [comment]
另外使用vrouter的时候不能同时使用有线/无线.会导致vrouter不显示启动.大概是没有同时对多个网卡分配网关

**Comment by icymind** [comment]
1.填192.168.1.2，如果finalspeed监听0.0.0.0，那填10.19.28.46也行，这ip不会变的。
2.同时有线无线的情况的确没有处理。因为手上没有有线的机器，也就懒了
