### ISSUE TITLE
关于ssr连接以及ss连接的导入

### ISSUE THREAD

**Issue by fanvinga** [icymind/VRouter#17]
希望作者能增加对于ssr/ss url形式导入的支持.或者至少在各种必填项中固定范围的加入选项支持.目前只能手写.出错可能性大.麻烦了

**Comment by icymind** [comment]
谢谢鞭策.
另外, 使用过程中有遇到什么bug吗? 反馈的人好少

**Comment by tingxueren** [comment]
不知道是不是我使用的问题，发现启动后，dns 的查询是有问题，无法在正常的访问

ss 版本
shadowsocks-libev 3.0.6

INFO: tcp server listening at 127.0.0.1:25000
NFO: udp server listening at 127.0.0.1:25000

tcp udp 都正常启动

![image](https://user-images.githubusercontent.com/2038464/28330186-3253a8da-6c1f-11e7-8e38-2985fba0ad9e.png)

**Comment by icymind** [comment]
@tingxueren 服务器那边的防火墙有没有放行25000端口的udp?

**Comment by tingxueren** [comment]
@icymind

**Comment by icymind** [comment]
@tingxueren 系统一栏中, "转发 DNS 查询: " 是不是"运行中"? 有可能转发dns查询的进程无法启动

**Comment by icymind** [comment]
@tingxueren 另外, 可以用其他$$的客户端进行排查. 比如在安卓客户端中勾选"DNS Forwarding"看看效果如何

**Comment by tingxueren** [comment]
@icymind 
![image](https://user-images.githubusercontent.com/2038464/28331162-a34000c2-6c22-11e7-817f-3d30ece6bd32.png)
这个都是在正常的，后续我用Android 再测试下吧，多谢

**Comment by tingxueren** [comment]
@icymind 我测试的结果是 ss-server 这个开启 tcp/udp 再套上 obfsproxy 能用，直接连接是失败的，
shadowsocks-go 版本，只支持 tcp 协议，启动后，所有的client都能用 。。。

**Comment by icymind** [comment]
@tingxueren 按理说libev不用套obfsproxy也可以用的, 我就是用的这个. 
不知道是不是地域/运营商的因素在作怪

**Comment by icymind** [comment]
导入配置: 0.3.x版本的todo
