### ISSUE TITLE
关于无法启动和一些建议

### ISSUE THREAD

**Issue by fanvinga** [icymind/VRouter#18]
1.我有有线和无线网卡.我如果同时开启的话.则看设置dns被设置为vrouter内部地址.能正常使用.关闭任意一个都可以.但是始终显示启用状态.但其实服务是正常启动了的.会有点不确定的感觉.
2.关于VRouter的退出.如果我直接点了vrouter的×.程序会直接退出.应该将关闭按钮设置为关闭当前窗口
3.关于增加DNS的设置.不知道是否可以增加一个这样的设置.因为不一定需要一定开启远程dns查询.有时候选一个无污染dns也可以的.而且比较建议能增加查询的dns.

**Comment by icymind** [comment]
谢谢反馈.
1. 多网卡的问题的确存在. 我争取找个usb网卡, 尽量fix.
2. 退出应用是故意这么设计的, 一来为了节能, 而来UI长时间运行一段时间后, 和后台虚拟机建立的ssh连接会断开. 结果是UI无法控制虚拟机
3. 只要是境外的DNS, 应该都会被污染吧?
