### ISSUE TITLE
代理页面点击Password显示密码按钮，上面未保存的文本框会恢复原状

### ISSUE THREAD

**Issue by CloudnuY** [icymind/VRouter#19]
如题
<img width="527" alt="2017-07-24 4 06 38" src="https://user-images.githubusercontent.com/14636247/28513792-18901a86-708a-11e7-82b7-fb428359bfbe.png">

点击一次“小眼睛”之后
<img width="527" alt="2017-07-24 4 07 23" src="https://user-images.githubusercontent.com/14636247/28513813-2d58c576-708a-11e7-8921-9e8fbb9f597f.png">

**Comment by icymind** [comment]
谢谢反馈, 的确存在这个问题. 下个commit修复

**Comment by icymind** [comment]
在 bf85250 中进行了修复: 

当处于编辑模式时, 禁用 "隐藏/显示" 按钮
