### ISSUE TITLE
切换失败后，DNS 未恢复成启动前的

### ISSUE THREAD

**Issue by cielpy** [icymind/VRouter#2]
点击切换，开始 loading，之后恢复成切换状态
![image](https://user-images.githubusercontent.com/3138493/27631486-2c95c652-5c2b-11e7-96c1-7d2e5e3ea6c8.png)

这个时候DNS 成了 10.19.28.37，不能正常解析域名

**Comment by icymind** [comment]
切换失败有提示吗? 每次都会失败吗?

切换成功的话, dns切成10.19.28.37是预期的结果.
可否把切换前和切换后的`netstat -nr`命令输出贴出来?

**Comment by cielpy** [comment]
失败没有提示，每次都是失败的

[切换后.txt](https://github.com/icymind/VRouter/files/1108287/default.txt)
[切换前.txt](https://github.com/icymind/VRouter/files/1108286/default.txt)

**Comment by icymind** [comment]
退出VRouter, 然后先用以下命令恢复系统网关:
```bash
# 查找你的路由器地址, 假设命令输出1.2.3.4
/usr/sbin/networksetup -getinfo Wi-Fi | grep Router

# 恢复网关, 1.2.3.4 恢复成你的路由器地址
sudo /sbin/route change default 1.2.3.4

# 恢复DNS
sudo networksetup -setdnsservers Wi-Fi 1.2.3.4

# 确认网关已恢复
/usr/sbin/netstat -nr | grep default | awk '{print $2}'

# 确认DNS已恢复
/usr/sbin/networksetup -getdnsservers Wi-Fi
```
恢复后再试试VRouter, 看看能不能正常切换

**Comment by cielpy** [comment]
还是不能切换

netstat -nr 输出：

[切换后.txt](https://github.com/icymind/VRouter/files/1108364/default.txt)
[切换前.txt](https://github.com/icymind/VRouter/files/1108365/default.txt)

**Comment by icymind** [comment]
按这个输出判断, 切换已经成功了. 默认路由已经从192.168.57.1切换成了VRouter的地址.

你是从哪里判断失败了呢?

如果是因为不能上网, 在默认路由和DNS都是10.19.28.37的情况下, 请依次排除:
- 通过"系统"标签页,查看"VRouter IP 地址"一栏, 可以获知VRouter是否已经成功从路由器获取IP. 如果没有获取到正确的IP地址, 那就要打开路由器的DHCP
- 请在"规则"标签页把模式改为"无代理", 应用. 然后访问国内网站看能不能使用.

**Comment by cielpy** [comment]
切换后

$ /usr/sbin/networksetup -getinfo Wi-Fi | grep Router
Router: 192.168.57.1
IPv6 Router: none

并且不能上网

使用 dig 提示超时

VRouter IP 为  192.168.57.114

**Comment by icymind** [comment]
我应该找到bug源头了. 再麻烦你把 `/usr/sbin/networksetup -getinfo Wi-Fi`的整个输出贴出来吧, 谢谢

**Comment by cielpy** [comment]
$ /usr/sbin/networksetup -getinfo Wi-Fi
DHCP Configuration
IP address: 192.168.57.166
Subnet mask: 255.255.255.0
Router: 192.168.57.1
Client ID:
IPv6: Automatic
IPv6 IP address: none
IPv6 Router: none
Wi-Fi ID: xx:xx:Xx:cd:22:02

我公司是禁止二级路由的，应该会有影响 VRouter 使用的吧，绑定 MAC 地址和 IP 的路由器才能上网


在 2017年6月28日 下午7:24:40, icymind (notifications@github.com) 写到:

我应该找到bug源头了. 再麻烦你把 /usr/sbin/networksetup -getinfo Wi-Fi的整个输出贴出来吧, 谢谢

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/icymind/VRouter/issues/2#issuecomment-311632017>, or mute
the thread

**Comment by icymind** [comment]
无法恢复系统默认路由的bug已经在v0.1.1中修复.

至于你无法上网的问题, 可能就在于贵司的政策了. 如果使用家里的wifi还不行, 请再反馈

**Comment by cielpy** [comment]
嗯，我猜是路由器限制的问题，我回去家里再看看

**Comment by icymind** [comment]
如果你可以申请到IP, 可以把Vrouter的mac地址提交给网管 😄

**Comment by cielpy** [comment]
- -! 算了，我已经架了一个实体路由在桌下了，一直找网管都不耐烦了
