### ISSUE TITLE
可以换成 xhyve 虚拟机么？

### ISSUE THREAD

**Issue by galaxy001** [icymind/VRouter#20]
xhyve 虚拟机应该占用更小，能换成它么？

**Comment by icymind** [comment]
暂时没这个计划. 基于virtualbox日后可以方便地向windows和linux移植. xhyve的话就是osx only了.

当然欢迎提交PR, 如果有人能维护基于xhyve的版本的话, 那最好不过了, 毕竟virtualbox还是有点重 😄
