### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by Kilerd** [icymind/VRouter#22]
1.  有没有开机自启的设置选项（自动启动VRouterHeadless，自动设置系统网关）
2. 代理设置里面，能不能提供一个列表选择，对于要经常切换服务器的人来说，要经常重新输入略显麻烦
3. 允许时的 log 显示？

我大致想表达的是，在Vrouter上，能不能显示更多的内容，而不是设置完了之后就没法做任何的操作。

**Comment by icymind** [comment]
1. todo
2. 已在0.3.0中添加
3. 暂时没想法
