### ISSUE TITLE
太赞了，忍不住开个issue，顺便提个想法

### ISSUE THREAD

**Issue by bitweng** [icymind/VRouter#23]
像黑白名单这种，如果可以指定 url 下载，就可以一起维护、共享了。
域名规则是否可以模糊匹配？像 *.cn 这样。

**Comment by icymind** [comment]
1. 黑白名单独立出来是个好主意, 但是已经有大名鼎鼎的gfwlist项目了, 再维护一个名单感觉不是很有必要
2.黑白名单是依赖dnsmasq来实现的, 暂时不能模糊匹配.
