### ISSUE TITLE
cannot resolve DNS queries

### ISSUE THREAD

**Issue by coderfox** [icymind/VRouter#24]
Client Information
-----

VRouter 信息

openwrt 版本: CHAOS CALMER (15.05.1, r48532) 
BR-LAN 地址: 10.19.28.37
VRouter IP 地址: 192.168.1.100 
VRouter mac 地址: 08:00:27:e0:b7:47
shadowsocks-libev 版本: 3.0.7
shadowsocksR-libev 版本: 2.5.6
kcptun 版本: 20170525

Bug
-----

```shell
$ nslookup google.com
;; connection timed out; no servers could be reached

$ nslookup baidu.com 
Server:		10.19.28.37
Address:	10.19.28.37#53

Non-authoritative answer:
Name:	baidu.com
Address: 220.181.57.217
Name:	baidu.com
Address: 123.125.114.144
Name:	baidu.com
Address: 111.13.101.208

$ nslookup twitter.com
;; connection timed out; no servers could be reached
```

I cannot query any blocked website's server address.

I am sure my server has UDP relay turned on.

**Comment by icymind** [comment]
防火墙放行udp包了吗?

**Comment by coderfox** [comment]
macOS 的防火墙处于关闭状态。

**Comment by icymind** [comment]
服务器的呢

**Comment by coderfox** [comment]
服务器是能用的，我之前用路由器架的是能转发 UDP 包的。

**Comment by icymind** [comment]
那你用安卓版ss试试, 打开安卓版的dns forwarding. 能否顺利连接google等网站

**Comment by coderfox** [comment]
已确认是服务器 UDP 转发策略的问题，已解决，抱歉打扰。
