### ISSUE TITLE
Cannot read property 'enableTunnelDns' of undefined

### ISSUE THREAD

**Issue by tkisme** [icymind/VRouter#26]
然后点击重试就挂了，必须删除
```
$ vboxmanage startvm vrouter --type emergencystop
$ VBoxManage unregistervm vrouter --delete
```

**Comment by tkisme** [comment]
![image](https://user-images.githubusercontent.com/5886048/29102821-49043362-7cee-11e7-9127-3707652feb9c.png)

**Comment by icymind** [comment]
谢谢大佬的反馈.
这个bug是因为用老版本的config.json构建vrouter导致的.


- 请删除后台虚拟机, 然后手动删除` ~/Library/Application Support/VRouter` 文件夹后再重新构建

或者

- 下载 0.3.0b 使用
