### ISSUE TITLE
从老版本升级后，使用有线网络报错

### ISSUE THREAD

**Issue by lxm** [icymind/VRouter#27]
使用有线网络时，报错，日志中错误如下{"message":"Cannot read property '1' of null","stack":"TypeError: Cannot read property '1' of null\n    at VRouter.changeBridgeAdapter (/Applications/VRouter.app/Contents/Resources/app.asar/js/vrouter-local.js:649:42)\n    at process._tickCallback (internal/process/next_tick.js:103:7)","level":"error","timestamp":"2017-08-14T09:25:22.911Z"}

**Comment by icymind** [comment]
谢谢反馈.

在你的终端里执行以下命令, 输出是什么?
```bash
cat <<EOF | scutil
open
get State:/Network/Global/IPv4
d.show
EOF
```

执行`VBoxManage list bridgedifs`的输出又是什么?

**Comment by lxm** [comment]
两个命令的输出分别如下
![image](https://user-images.githubusercontent.com/1918195/29268399-2c1468e6-811f-11e7-8135-e49461678e5a.png)
![image](https://user-images.githubusercontent.com/1918195/29268424-472ee386-811f-11e7-9890-348e2961814c.png)

**Comment by lxm** [comment]
刚调试了一下确定原因，getActiveAdapter 拿到的servicename为Ethernet，而/usr/local/bin/VBoxManage list bridgedifs命令的结果返回的连接名称为`Name:            en0: 以太网`
此名称没有人为改过，目前修改getActiveAdapter
```
    const serviceName = await this.localExec(cmd)
    if (serviceName.trim() == 'Ethernet'){
      serviceName = '以太网'
    }
    return [serviceName.trim(), inf, router]
```
可以正常运行安装过程，不知道是不是我本地的问题

**Comment by icymind** [comment]
并不是你的问题。我写的时候没考虑到中英文系统的差异

**Comment by icymind** [comment]
并不是你的问题, 是我没考虑到中英文系统的差异

**Comment by icymind** [comment]
mbp里没有"以内网", 能否麻烦你贴一下`networksetup -listnetworkserviceorder`的输出?

**Comment by lxm** [comment]
```
 ~  networksetup -listnetworkserviceorder
An asterisk (*) denotes that a network service is disabled.
(1) Ethernet
(Hardware Port: Ethernet, Device: en0)

(2) Wi-Fi
(Hardware Port: Wi-Fi, Device: en1)

(3) Bluetooth PAN
(Hardware Port: 蓝牙 PAN, Device: en4)
```
环境为mac mini
```
VBoxManage list bridgedifs 命令的时候，为以太网
```

```
Name:            en0: 以太网
GUID:            00306e65-0000-4000-8000-ac87a32c7ab6
DHCP:            Disabled
IPAddress:       192.168.0.54
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-en0
```

我提交了一个PR， 你可以看下我的修改

**Comment by icymind** [comment]
Fixed via a302702
