### ISSUE TITLE
why not use DHCP and LEDE?

### ISSUE THREAD

**Issue by lioliy** [icymind/VRouter#29]
看了下原理通过改路由和网关的方式实现全局代理,比较麻烦，为什么不直接使用dhcp服务器直接进行分配ip呢？
openwrt上开dhcp服务器，Mac 上`sudo ipconfig set vmnetx DHCP`，vmnetx是虚拟网卡，这样Mac会自动的分配一个IP地址，就全局上网了。也可以改preferences向网络设置上加个可控界面,这样就全自动分配了
![2246597F-0137-4481-BF50-272B3AF07CA1.png](https://i.loli.net/2017/08/15/59924d834cdde.png)

LEDE个人感觉更稳定些

**Comment by icymind** [comment]
抱歉没能领会你的意思, 能阐述清楚一些吗?

虚拟网卡获取IP后, 接下来怎么让osx里的某个应用通过openwrt里的代理上网呢?

**Comment by lioliy** [comment]
某个应用，你说是分应用吗？你做的是全局代理啊。
加入dhcp就是自动分配，openwrt里是透明代理，mac上分配后也走的透明代理

**Comment by icymind** [comment]
ok, 我懂了. 你的意思是不是说, 假设物理路由器是192.168.1.1, 虚拟openwrt是192.168.0.1

现在osx有两块网卡, 物理网卡分配到192.168.1.100, 虚拟网卡分配到192.168.0.100
但是如果不更改网关的话, 数据怎么会流向openwrt呢? 毕竟现在你有两块网卡.

(系统默认的网关应该是192.168.1.1吧, 不确定)

**Comment by lioliy** [comment]
物理网卡不进行分配就行了，仅供虚拟机用

**Comment by icymind** [comment]
你是成功这么做了对吗?
vrouter后台的虚拟机需要桥接宿主的物理网卡上网, 如果宿主的物理网卡不上网, 我不知道虚拟机如何联网.
能说说你的网络拓扑吗

**Comment by fanvinga** [comment]
@icymind 他这个思路应该是这样的
无VROUTER：实际路由器-物理网卡-mac（网卡分配到的ip）
他设想：实际路由器-物理网卡-vrouter（接收网卡分配ip）-mac（接收vrouter分配的ip）
但正如作者所说.怎么让mac从原来的物理网卡作为网关切换到用vrouter作为网关.不过据我观察现在应该就是这样的吧

**Comment by lioliy** [comment]
物理网卡起链路作用，就是给虚拟机连上路由器，但主机不进行ip地址分配，主机使用虚拟机的dhcp进行分配即可，这样就不纠结主机的网关了

**Comment by lioliy** [comment]
┌─────────────────┐                            
                                       │Host (Mac device)│                            
                                       └────────▲────────┘                            
                                                │                                     
                                                │                                     
                                                │                ┌ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┐
                                        ┌───────▼────────┐            ┌──────────┐    
                                 ┌──────│vrouter    (VM1)│◀────┬─┼───▶│   VM2    │   │
                                 │      └───────▲────────┘     │      └──────────┘    
                                 │                             │ │                   │
                                 │              │              │      ┌──────────┐    
                                 │                             ├─┼───▶│   VM3    │   │
                                 │              │              │      └──────────┘    
                 ┌─────────┐     │                             │ │                   │
                 │ Router  │─────┤              │              │      ┌──────────┐    
                 └─────────┘     │                             ├─┼───▶│   VM4    │   │
                                 │              │              │      └──────────┘    
                                 │                             │ │                   │
                                 │              │              │      ┌──────────┐    
                                 │                             └─┼───▶│   VMN    │   │
                                 │              │                     └──────────┘    
                                 │       ┌──────▼──────┐         └ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┘
                                 └────── │Other Devices│                Virtual       
                                         └─────────────┘                Machines

**Comment by icymind** [comment]
如果做到"主机不进行ip分配"?

**Comment by icymind** [comment]
试了一下, 在osx网络设置里把dhcp关掉. 物理网卡是没有没有网络连接, 虚拟机还是可以通过物理网卡桥接上网. 我以前一直以为必须桥接到的网络也必须要有 IP 才行, 看来是太错了. 谢谢斧正!

如果采用这种拓扑, 就必要要求后台虚拟机一直运行. 想暂停使用的话, 虽然不用更改网关了, 但是要把dhcp再打开. 对比原来的拓扑, 暂停使用vrouter的话也只是更改一下默认路由, 新拓扑并没有减少需要操作的步骤.

我现在能想到的优势就是, 新拓扑只需要一个 IP, 这在某些场合还是很方便的.

还有什么我没想到的优点吗?

**Comment by lioliy** [comment]
不用那么麻烦，只需要更改preferences.plist就可以做到，用户切换时只需要在苹果菜单点击网络位置即可。如图![B0EE88C1-0F99-47AF-9527-C0DB72C22BF4.png](https://i.loli.net/2017/08/18/5996678143ea7.png)
暂停使用仅需切换为普通网络，这样做的优点我认为是方便切换，不用手动更改路由，openwrt启动dhcp服务器，方便为Mac上其他虚拟机使用，全局代理，无需配置（可选）

**Comment by icymind** [comment]
谢谢, 不过暂时不考虑你的方案.
本来只需要在应用里点一下"暂停/启用"按钮, 现在添加一个新的位置, 用户还需要去点击系统里的按钮进行切换. 我并不认为能方便多少
