### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Cavolo** [icymind/VRouter#30]
对windows系统的支持开发现在优先级怎么样呢，windows上才是真正比较缺乏这类应用的

**Comment by icymind** [comment]
优先级很低.

可以了解下你在window下的需求吗?

**Comment by Cavolo** [comment]
windows下有大量软件不支持自定义代理，例如steam里面的游戏走的udp在win上没有好的解决方案，而相反mac感觉已经有surge这类软件已经实现了

**Comment by icymind** [comment]
我试过代理udp玩csgo, 延迟比不用代理还大. 所以除非你有台延迟低的服务器, 不然不要对游戏加速抱太大希望😂

Windows版要在重构完代码后才进行, 现在的代码实在太恶心了

**Comment by fanvinga** [comment]
我个人认为win对于这类透明代理的需求更高.win设置系统代理复杂.而且基本上很多应用都不走代理.一个一个设置繁杂困难

**Comment by Cavolo** [comment]
Mac上透明代理的软件现对较多，win上这方面基本是个空白。如果这个项目成为win上第一个较易用的软件，会使这个项目发展的更有活力吧

**Comment by lzwhuhu** [comment]
您好，我看了您https://icymind.com/virtual-openwrt/的文章之后在windows上成功建立了这个虚拟路由器，但是所有uwp应用都无法联网，chrome这样普通应用没问题，请问有什么应对措施呢？

**Comment by lzwhuhu** [comment]
您好，我看了您[https://icymind.com/virtual-openwrt/](https://icymind.com/virtual-openwrt/)的文章之后在windows上成功搭建了虚拟路由器，所有win32应用比如chrome什么的都能正常上网，但是所有uwp应用都上不了网，但一直没找出哪里出了问题，请问可能是哪方面的原因？

**Comment by icymind** [comment]
@lzwhuhu  
1. 只留一个物理网卡, 其他的禁用
2. 把唯一的物理网卡的ipv4禁用
3. 把默认网关改为虚拟机的ip

试试以上办法, 应该可以

**Comment by lzwhuhu** [comment]
我按照您说的修改之后chrome和其他win32应用能连上网络，但是windows设置提示没有网络连接，edge也提示没有网络连接，之前edge提示的是“发生临时 DNS 错误“，我觉得可能是设置默认网关那出了问题，我再多试试整理一下问题，非常感谢

**Comment by lzwhuhu** [comment]
好像是uwp应用根本访问不了虚拟机的地址，和设置没关系

**Comment by lzwhuhu** [comment]
最后在更改适配器选项里把虚拟网卡和Wlan桥接了一下，把桥接出来的网卡默认网关设置成虚拟机ip就成了，非常感谢

**Comment by icymind** [comment]
当前开发进度: dev 分支已经可以在 windows 下构建虚拟机

@lzwhuhu 能说一下如何设置桥接网卡的网关吗?

**Comment by lzwhuhu** [comment]
@icymind 是GUI，我就桥接了一下两个网卡，然后把网桥的默认网关改成了openwrt的，然后成功了谷歌百度都秒开，不过仅维持了5分钟左右就完全上不了网了，一直找不到问题，后来从头设置虚拟机重新设置网关也没能成功，弄了好久一直不行有些沮丧后来一直没有再弄「捂脸」

**Comment by icymind** [comment]
@lzwhuhu 嗯. edge 和 uwp 是特例, 他们死活都不走 virtualbox adapter.
chrome 和 其他应用倒是正常

**Comment by lzwhuhu** [comment]
@icymind 对对对！不过桥接网卡那个方法确实让edge成功走了一小会儿openwrt，然而后来就无法重现了，有些迷‘_>`

**Comment by icymind** [comment]
发布了支持 windows 的版本: https://github.com/icymind/VRouter/releases/tag/v0.4.0-alpha
欢迎提交反馈

**Comment by icymind** [comment]
@Cavolo 朋友你可以去试试 SSTap 吗? 在你看来它怎么样呢
