### ISSUE TITLE
About BREW

### ISSUE THREAD

**Issue by fanvinga** [icymind/VRouter#31]
不知道作者有没有想过把vrouter放到brew cask上面来达到自动安装？

**Comment by icymind** [comment]
暂时没计划, 至少 1.0 以前都不会做

**Comment by qiwihui** [comment]
@fanvinga 已经帮着添加了一个brew cask了，使用`brew cask install vrouter`即可安装

**Comment by fanvinga** [comment]
@qiwihui 在cask的commit history看到了你的提交哈哈.我看看删除部分会不会有残留文件.帮助改进下:-D
