### ISSUE TITLE
How to uninstall it?

### ISSUE THREAD

**Issue by VoganWong** [icymind/VRouter#37]
My Mac installed it yesterday, but I found that I didn't need it. 

And now my network environment has changed, I do not know how to set it default.

**Comment by VoganWong** [comment]
Obviously, my DNS has been changed. I cannot access websites in LAN.

**Comment by icymind** [comment]
打开应用，点击系统，点击“更多”，点击删除

**Comment by icymind** [comment]
也可以手动恢复网关，方法在wiki
