### ISSUE TITLE
安装了，启动了，没有提示任何错误，但就是上不了网，请问如何 debug ？

### ISSUE THREAD

**Issue by gdtv** [icymind/VRouter#38]

**Comment by gdtv** [comment]
今天又试了，可以上网，但是流量不走代理。
这是日志：

> 2017-09-07T18:23:22+08:00 - debug: about to connect to openwrt via ssh
> 2017-09-07T18:23:22+08:00 - info: bridgeServices: Realtek PCIe GBE Family Controller,TAP-Windows Adapter V9,Remote NDIS based Internet Sharing Device,Intel(R) WiFi Link 5100 AGN,SAMSUNG Mobile USB Remote NDIS Network Device,Intel(R) 82567LM Gigabit Network Connection
> 2017-09-07T18:23:22+08:00 - info: actived Bridge Service: Realtek PCIe GBE Family Controller
> 2017-09-07T18:23:25+08:00 - debug: about to getAssignedHostonlyInf of vrouter. very slow on windows platform
> 2017-09-07T18:23:26+08:00 - debug: getAssignedHostonlyInf: VirtualBox Host-Only Ethernet Adapter #2
> 2017-09-07T18:23:26+08:00 - debug: Router IP: 192.168.1.1

**Comment by icymind** [comment]
当前网关/当前DNS是什么?

进程状态又是如何?
