### ISSUE TITLE
Win7下的配置文件错误

### ISSUE THREAD

**Issue by renzhn** [icymind/VRouter#41]
在我这里，手动修复以下错误才能正常运行：
1. 需要把/etc/vrouter里面shadowsocks/tunnelDns等ss相关配置里面fast open的值从加引号的true改为不加引号，否则会出现值不是boolean的错误。
2. 需要把proxies_watchdog里面[object Object]改为tunnelDns等。

**Comment by icymind** [comment]
非常感谢!

**Comment by icymind** [comment]
fixed via https://github.com/icymind/VRouter/commit/3d58902e7490d5e9971e89637a18ac0ca9d375a7
