### ISSUE TITLE
invalid config file: option 'fast_open' must be a boolean

### ISSUE THREAD

**Issue by gdtv** [icymind/VRouter#45]
### VRouter 版本
0.4.0
### 操作系统版本
windows10 1703

问题一：
启动后，VRouter 应用内, "系统"标签页显示ssr已启动，但主机上不了网。
在虚拟机内执行
`ssr-redir -c /etc/vrouter/shadowsocksr.json `
显示：
`invalid config file: option 'fast_open' must be a boolean.`
在虚拟机内执行
`cat /etc/vrouter/shadowsocksr.json` 
显示：
`'fast_open': 'false' (注意false的外面有括号)`

去到VRouter 应用内修改ssr设置里的fast open为brue（在下拉列表里选择）
然后再在虚拟机内执行
`cat /etc/vrouter/shadowsocksr.json `
显示：
`'fast_open':  true (注意false的外面没有括号)`
然后再启动系统，可以代理上网了。

问题二：
关闭VRouter 应用后，虚拟机还会在后台运行？ 要手动去virtualbox里关闭虚拟机才行？ 

问题三：
请问怎样查看ss、ssr的运行、错误日志？ 如果ss、ssr出问题怎样debug？

**Comment by lanx-x** [comment]
谢谢反馈.
1. invalid config 已经在beta2修复了, 你可能是从beta升上来的, 所以遗留了这个问题. 现在还能复现吗?
2. vrouter 里有关闭虚拟机的按钮, 退出vrouter没有关闭虚拟机.
3. 默认不保存代理运行的日志. debug 可以先关闭进程后, 添加`-vv`手动启动: `ss-redir -c /etc/vrouter/shadowsocks.json -vv`
