### ISSUE TITLE
关于SSR的订阅链接支持增加

### ISSUE THREAD

**Issue by fanvinga** [icymind/VRouter#48]
大佬你好.我又来叨扰你了(´･ω･`)
这次是关于SSR订阅链接的支持.现在为了方便导入/更新节点.很多人都在用订阅的方式导入SSR配置.不知道是否可以考虑增加支持？
如有需要我可以提供sample

**Comment by lanx-x** [comment]
国庆快乐! 暂时没这个这个计划呢. 不过欢迎提交 PR 😄
