### ISSUE TITLE
tar:can't open '/etc/com.icymind.vrouter/third_party/kcptun*.tar.gz':No such..

### ISSUE THREAD

**Issue by lerry** [icymind/VRouter#5]
![qq20170630-094524](https://user-images.githubusercontent.com/1225368/27729670-3fa97718-5db9-11e7-8406-8f23b053b3ff.png)

**Comment by icymind** [comment]
你从源码运行的吧？我提交代码的时候，gitignore把kcptun的压缩包忽略掉了，你去官网下载个放到third_party文件夹内就好。
从release下载运行应该没这个问题
