### ISSUE TITLE
请求支持SS原版的simple-obfs混淆插件

### ISSUE THREAD

**Issue by shikkoku** [icymind/VRouter#55]
https://github.com/shadowsocks/simple-obfs

https://github.com/aa65535/openwrt-simple-obfs

**Comment by lanx-x** [comment]
add obfs support via d51b9e1a8cb5553d3102a23a22c6b0766d67dd70 ~ 17c07c8ed6af4ac02da71bedb24007cc4816cd1e

**Comment by shikkoku** [comment]
似乎0.4.2版开始提供支持了，但Windows版没有预编译版？
