### ISSUE TITLE
Vrouter是否成为便携软件

### ISSUE THREAD

**Issue by sagasm** [icymind/VRouter#56]
我有台win10机器，装了多次尝试无法安装VRouter  0.4.1，想把另外一条win7上安装好的VRouter拷贝过去该请问如何操作？

**Comment by lanx-x** [comment]
或者你可以贴出出错信息, 我可以帮你看看为什么无法安装.

导入导出的话用 virtualbox 自带的就行, 从 virtualbox 导出虚拟机, 然后在 win7 上导入

**Comment by sagasm** [comment]
虚拟机转移我会操作，但是我感觉VRouter启动配置和设置网卡路由的功能应该不是由虚拟机操作的吧

**Comment by lanx-x** [comment]
构建过程和设置路由是独立的，只要后台存在虚拟机，就能跳过构建过程。设置路由前vrouter会进行一些必要的检查(检查虚拟网卡什么的), 发现问题的话会尝试纠正(比如新建一个虚拟网卡, 配置虚拟网卡什么的)
