### ISSUE TITLE
mac 睡眠后需要重新手动启动才可正常使用网络

### ISSUE THREAD

**Issue by Kilerd** [icymind/VRouter#58]
### VRouter 版本
0.4.1
### 操作系统版本
OS X 10.13
### VRouter 应用内, "系统"标签页的信息
 系统信息
当前网关: 10.19.28.37
当前 DNS: 10.19.28.37
VRouter 信息
WAN: 192.168.1.24
BR-LAN: 10.19.28.37
Bridged Network: en0: Wi-Fi (AirPort)
Mac Address: *
Openwrt Version: 15.05.1
Shadowsocks Version: 3.1.0
ShadowsocksR Version: 2.5.6
Kcptun Version: 20170904

具体问题在于： 睡眠前正常使用，睡眠后无法访问网络，需要手动打开 Vrouter 的 GUI 界面，然后这时候GUI显示的是“未启动状态”，需要手动去点“启动”

**Comment by lanx-x** [comment]
电脑从睡眠中恢复时, 系统会将默认网关修改为物理路由器.
VRouter 每隔几分钟会检查一遍 dns 和网关, 发现两者不一致的话会自己修正.
唤醒后你稍等10分钟
