### ISSUE TITLE
镜像源挂了么，构建错误似乎下载镜像超时

### ISSUE THREAD

**Issue by qiudaomao** [icymind/VRouter#61]
### VRouter 版本
0.4.1

### 操作系统版本
macOS10.13

### VRouter 应用内, "系统"标签页的信息
没进去
Error: connect ETIMEDOUT 101.6.6.177:443
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)

**Comment by lanx-x** [comment]
嗯，暂时上不去了

**Comment by tkizm1** [comment]
改config.json并没有影响下载地址，令人窒息。。

**Comment by qiudaomao** [comment]
已经手动装好了openwrt，看来暂不需要用这个前端了
建议添加一些错误处理
现在如果安装过程失败，下一次并不会自动尝试重新安装，而是直接认为虚拟机创建好了，然后各种操作错误…
需要手动打开VirtualBox删除这个vrouter虚拟机才会重新尝试安装...

**Comment by tkizm1** [comment]
出现 Error: connect ETIMEDOUT 101.6.6.177:443 错误时，点击重试前必须手动打开VirtualBox，手动启动虚拟机
不然出现Error: Command failed: /usr/local/bin/VBoxManage controlvm vrouter poweroff

**Comment by lanx-x** [comment]
@tkisme 嗯， 目前构建阶段采用的时源码里的 config.json，所以改用户的 config.json不会有什么效果

**Comment by lanx-x** [comment]
@fuzhuo 构建过程如果失败， 是有“删除并退出”的按钮的，点了之后虚拟机会被删除

**Comment by lanx-x** [comment]
镜像站已经恢复。关闭这个 issue， 有其他问题请另外提交吧:smile:
