### ISSUE TITLE
麻烦请教 up 主, 想更新 ssr 怎么办呢?目前版本测试没有 auth_chain_a

### ISSUE THREAD

**Issue by oit63** [icymind/VRouter#72]
### VRouter 版本
最新

### 操作系统版本
mac os 10.13

### 暂停 VRouter 后, 以下命令(可一起执行)的执行结果
- macOS: nslookup qq.com;/sbin/route -n get default;tail -n 50 ~/Library/Application\ Support/vrouter/vrouter.log
- Windows ( 请用 PowerShell 执行 ): nslookup qq.com;tracert -d -w 1000 -h 5 qq.com;Get-Content ~/AppData/Roaming/vrouter/vrouter.log  -tail 50 -Encoding UTF8

### 启用 VRouter 后, 以下命令(可一起执行)的执行结果
- macOS: nslookup qq.com;/sbin/route -n get default;tail -n 50 ~/Library/Application\ Support/vrouter/vrouter.log
- Windows ( 请用 PowerShell 执行 ): nslookup qq.com;tracert -d -w 1000 -h 5 qq.com;Get-Content ~/AppData/Roaming/vrouter/vrouter.log  -tail 50 -Encoding UTF8

**Comment by leoleoasd** [comment]
神他妈up主

**Comment by oit63** [comment]
随身带个路由，在路由上翻好。这个还是不用了，占用笔记本资源。
