### ISSUE TITLE
启动以后，整个界面空白

### ISSUE THREAD

**Issue by c1024** [icymind/VRouter#8]
下载v0.1.1版本，安装后启动，界面空白。系统是OS X 10.11.6

**Comment by icymind** [comment]
0.1.0能用吗?

**Comment by c1024** [comment]
我是复制0.1.1到 Application 文件夹运行测试的

**Comment by c1024** [comment]
我下载0.1.0,在dmg文件里双击也是不行

**Comment by icymind** [comment]
electron做的东西, 可能是因为加载有点慢. 白屏你大概等了多久?
要命的是我还没加上log, 所以白屏还真不知道问题出在哪.

你可以git clone代码下去, 然后用`npm start`运行, 这样可以用`option+cmd+i`快捷键打开console, 或许能找到问题.

log功能下一版加上

**Comment by c1024** [comment]
@icymind 刚才有事，离开电脑一个多小时，期间 程序开着，回来后发现界面出来了。。。

**Comment by icymind** [comment]
一个小时...可能是被黑得最惨的一次 😭

**Comment by c1024** [comment]
@icymind 观察了一下，应该不要一小时，应该最多10分钟左右就可以了，之前没等那么久，直接关掉了。不过构建完，每次启动还要挺久的。

**Comment by icymind** [comment]
jquery引用了google字体, 下载不下来就白屏了.
待修复

**Comment by icymind** [comment]
fixed by da6e53acbe3ff66b231727b661ade270cea7f938
