### ISSUE TITLE
permission denied: ssr-redir

### ISSUE THREAD

**Issue by tkisme** [icymind/VRouter#9]

**Comment by icymind** [comment]
谢谢反馈.
两种解决方法:
1. 登录后台虚拟机, 给ssr-redir等文件添加执行权限
```bash
chmod +x /usr/bin/kcptun /usr/ssr-*
```
2. 或者下载0.2.1使用

**Comment by icymind** [comment]
fixed by 0.2.1
https://github.com/icymind/VRouter/releases/tag/0.2.1
